### ISSUE TITLE
Add Node.js code samples for each feature described in the README

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/hitc-new-in-redis-62#3]
The README for this repository shows how to use some of the new Redis features from version 6.2 using `redis-cli`.  Add a folder called `nodejs` to this repo containing a single Node script that demonstrates each of these features using the same commands shown in the README.  Use the [node-redis](https://github.com/redis/node-redis) client for this, don't add any other dependencies.  Be sure to add a README file in the `nodejs` folder that explains how to install dependencies and run your script, and don't forget to commit `package.json` and `package-lock.json`.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by Mephalich** [comment]
@simonprickett @SuzeShardlow 
I could grab this task.

**Comment by simonprickett** [comment]
@Mephalich I've assigned this to you, looking forward to seeing your PR in the next couple of days. Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/
