### ISSUE TITLE
Add Python code samples for each feature described in the README

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/hitc-new-in-redis-62#4]
The README for this repository shows how to use some of the new Redis features from version 6.2 using `redis-cli`.  Add a folder called `python` to this repo containing a single Python script that demonstrates each of these features using the same commands shown in the README.  Use the [redis-py](https://github.com/redis/redis-py) client for this, don't add any other dependencies.  Be sure to add a README in the `python` folder the describes how to run your code in a Python virtual environment, and to commit a `requirements.txt` file for use with `pip`.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by kavyabhat02** [comment]
Hi @simonprickett @SuzeShardlow , I'd like to try my hand at this task! Could I please be assigned to this issue?
